name: ip Comment

on: 
  pull_request:
    branches: ["*"]

jobs:
  Comment:
   runs-on: ubuntu-latest
   steps:
     - env:
         PR_NUMBER: ${{ github.event.pull_request.number }}
       
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
        export body=$(curl 'https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true')
        export timezone=$(echo $body | jq '.timezone')
        export temperature=$(echo $body | jq '.temperature[0]')
        gh pr comment $PR_NUMBER --body "In $timezone Country/city, the temperature $temperature" --repo $GITHUB_REPOSITORY
